run:
  name: 48_wAT_entsoe_2030NT_apollo_fa_sp
  disable_progressbar: false
  shared_resources:
    policy: false
  shared_cutouts: true

scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - "adm"
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2030
  # 2020 / 2030 / 2040 / 2050 #gilt nur für Sektorkopplung
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

load:
  manual_adjustments: true # false
  scaling_factor: 1.315
  fixed_year: false # false or year (e.g. 2013) entspriicht dem snapshot jahr wenn false

electricity:
  estimate_renewable_capacities:
    enable: true
    from_gem: true
    year: 2020
    expansion_limit: 2 # zum beispiel 1.1  für 110%

lines:
  reconnect_crimea: false
  max_line_rating: false
  max_extension: 0 #MW

links:
  max_extension: 0 #MW
  p_min_pu: -1.0

transmission_projects:
  enable: true
  include:
    tyndp2020: false
    nep: false
    manual: true
  skip:
  - upgraded_lines
  - upgraded_links
  - new_lines
  #- new_links
  status:
  - apo
  #- aponew 
  #- in_permitting
  #- confirmed
  #- planned_not_yet_permitted
  #- under_construction
  #- under_consideration 
  new_link_capacity: keep #keep or zero

enable:
  retrieve: true
  retrieve_databundle: true
  retrieve_cost_data: true
  retrieve_cutout: true

clustering:
  mode: administrative
  administrative:
    level: bz
 
  temporal:
    resolution_elec: 1h
         
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'
  
atlite:
  default_cutout: europe-2013-sarah3-era5

costs:
  year: 2030

solving:
  solver:
    name: gurobi
    options: gurobi-default
  solver_options:
    gurobi-default:
      threads: 32
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200