# config/MA/config.128_wAT_entsoe_MA.yaml

run:
  name: 128_wAT_entsoe_MA
  disable_progressbar: false
  shared_resources:
    policy: true
  shared_cutouts: true

scenario:
  simpl: [""]
  ll: [vopt]
  clusters: [128]
  opts: [""]
  sector_opts: [""]
  planning_horizons: [""]

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

countries:
- AL
- AT
- BA
- BE
- BG
- CH
- CZ
- DE
- DK
- EE
- ES
- FI
- FR
- GB
- GR
- HR
- HU
- IE
- IT
- LT
- LU
- LV
- ME
- MD
- MK
- NL
- "NO"
- PL
- PT
- RO
- RS
- SE
- SI
- SK
- UA

electricity:
  custom_powerplants: true
  co2limit: 95900000.0
  co2base: 1918000000.0

lines:
  reconnect_crimea: false
  under_construction: remove

links:
  under_construction: remove

transmission_projects:
  enable: true
  include:
    tyndp2020: false
    nep: false
    manual: false
  skip:
    - upgraded_lines
    - upgraded_links
  status:
    - under_construction
    - in_permitting
    - confirmed
  new_link_capacity: zero

enable:
  retrieve: true
  retrieve_databundle: true
  retrieve_cost_data: true
  retrieve_cutout: true

clustering:
  focus_weights:
    AT: 0.4
  simplify_network:
    to_substations: false
    remove_stubs_across_borders: true
  cluster_network:
    algorithm: kmeans
    hac_features:
      - wnd100m
      - influx_direct
  temporal:
    resolution_elec: 6H

solving:
  solver:
    name: gurobi #highs #gurobi
    options: gurobi-default-threads #highs-default #gurobi-default-threads
  solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/dev/options/definitions/
      threads: 0 #0 means automatic #1
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
    highs-simplex:
      solver: "simplex"
      parallel: "on"
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      random_seed: 123
    gurobi-default-threads:
      threads: 20
      method: 2
      crossover: 0
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
    cplex-default:
      threads: 4
      lpmethod: 4
      solutiontype: 2
      barrier.convergetol: 1.e-5
      feasopt.tolerance: 1.e-6
    copt-default:
      Threads: 8
      LpMethod: 2
      Crossover: 0
      RelGap: 1.e-6
      Dualize: 0
    copt-gpu:
      LpMethod: 6
      GPUMode: 1
      PDLPTol: 1.e-5
      Crossover: 0
    cbc-default: {}
    glpk-default: {}
  mem_mb: 30000
  memory_logging_frequency: 30
  runtime: 6h

### additional parameters

case: "MA"

austria:
  shapefiles:
    buses: "data/shapefiles/buses_aut.shp"
    lines: "data/shapefiles/lines_aut.shp"
  output_network: "resources/networks/austria.nc"
  residual_loads:
    scenario: "NIP2030"
    sim_year: 2013
    input_dir: "data/MA/loads"
    inputs:
      nachfrage: "{input_dir}/{scenario}/Nachfrage.csv"
      pv: "{input_dir}/{scenario}/PV.csv"
      wind: "{input_dir}/{scenario}/Wind.csv"
      biomasse: "{input_dir}/{scenario}/biomasse.csv"
      gross_wasserkraft: "{input_dir}/{scenario}/GrossWasserkraft.csv"
      klein_wasserkraft: "{input_dir}/{scenario}/Kleinwasserkraft.csv"
add_electricity_base_network: "resources/networks/base_s_{clusters}_elec_residualloadadd.nc"
solve_network_input: "resources/networks/base_s_{clusters}_elec_residualload.nc"